package com.spi.framework.core

import java.util.ServiceLoader

/**
 * Main entry point for the SPI framework.
 * SPI 框架的主入口点。
 *
 * Discovers registered service implementations and provides access to them.
 * Uses [java.util.ServiceLoader] under the hood to discover [ServiceIndexProvider]
 * implementations generated by the KSP processor.
 * 发现已注册的服务实现并提供对它们的访问。
 * 底层使用 [java.util.ServiceLoader] 来发现由 KSP 处理器生成的 [ServiceIndexProvider] 实现。
 *
 * ## Quick Start / 快速开始
 *
 * 1. Define a service interface / 定义服务接口:
 * ```kotlin
 * interface GreetingService {
 *     fun greet(): String
 * }
 * ```
 *
 * 2. Annotate implementations / 注解实现类:
 * ```kotlin
 * @ServiceProvider(service = GreetingService::class, priority = 10, name = "english")
 * class EnglishGreeting : GreetingService {
 *     override fun greet() = "Hello"
 * }
 * ```
 *
 * 3. Load and use / 加载并使用:
 * ```kotlin
 * SpiLoader.initialize()
 * val service = SpiLoader.load(GreetingService::class.java)
 * println(service.greet())
 * ```
 *
 * ## Thread Safety / 线程安全
 *
 * All methods are thread-safe. [initialize] uses double-checked locking
 * and is safe to call from multiple threads simultaneously.
 * 所有方法都是线程安全的。[initialize] 使用双重检查锁定，
 * 可安全地从多个线程同时调用。
 */
object SpiLoader {

    private val registry = ServiceRegistry()

    @Volatile
    private var initialized = false

    private val initLock = Any()

    /**
     * Initialize the service registry by discovering all [ServiceIndexProvider]
     * implementations via [ServiceLoader].
     * 通过 [ServiceLoader] 发现所有 [ServiceIndexProvider] 实现来初始化服务注册表。
     *
     * This method is idempotent — subsequent calls are no-ops.
     * It is thread-safe and uses double-checked locking.
     * 此方法是幂等的——后续调用不会产生任何效果。
     * 它是线程安全的，并使用双重检查锁定。
     *
     * @param classLoader the [ClassLoader] to use for discovery.
     *   Defaults to the current thread's context class loader.
     *   用于发现的 [ClassLoader]。默认为当前线程的上下文类加载器。
     */
    fun initialize(classLoader: ClassLoader = Thread.currentThread().contextClassLoader) {
        if (initialized) return
        synchronized(initLock) {
            if (initialized) return
            val providers = ServiceLoader.load(
                ServiceIndexProvider::class.java,
                classLoader
            )
            providers.forEach { provider ->
                provider.initialize(registry)
            }
            initialized = true
        }
    }

    /**
     * Ensure the registry is initialized, calling [initialize] if necessary.
     * 确保注册表已初始化，必要时调用 [initialize]。
     */
    private fun ensureInitialized() {
        if (!initialized) {
            initialize()
        }
    }

    /**
     * Load the highest-priority implementation of [serviceClass].
     * 加载 [serviceClass] 的最高优先级实现。
     *
     * @param T the service interface type. 服务接口类型。
     * @param serviceClass the service interface [Class]. 服务接口的 [Class]。
     * @return the highest-priority implementation instance. 最高优先级的实现实例。
     * @throws ServiceNotFoundException if no implementation is registered. 如果没有注册任何实现。
     */
    fun <T : Any> load(serviceClass: Class<T>): T {
        ensureInitialized()
        return registry.getService(serviceClass)
            ?: throw ServiceNotFoundException(
                "No implementation registered for ${serviceClass.name}. " +
                "Ensure the implementation class is annotated with @ServiceProvider " +
                "and the spi-compiler KSP processor is applied to the module."
            )
    }

    /**
     * Load all implementations of [serviceClass], ordered by priority descending
     * (then by implementation class name for deterministic ordering).
     * 加载 [serviceClass] 的所有实现，按优先级降序排列（优先级相同时按实现类名排序以确保确定性顺序）。
     *
     * @param T the service interface type. 服务接口类型。
     * @param serviceClass the service interface [Class]. 服务接口的 [Class]。
     * @return a list of all implementation instances, or an empty list if none.
     *         所有实现实例的列表，如果没有则返回空列表。
     */
    fun <T : Any> loadAll(serviceClass: Class<T>): List<T> {
        ensureInitialized()
        return registry.getServices(serviceClass)
    }

    /**
     * Load a specific named implementation of [serviceClass].
     * 加载 [serviceClass] 的指定名称实现。
     *
     * @param T the service interface type. 服务接口类型。
     * @param serviceClass the service interface [Class]. 服务接口的 [Class]。
     * @param name the logical name specified in
     *   [com.spi.framework.annotations.ServiceProvider.name].
     *   [com.spi.framework.annotations.ServiceProvider.name] 中指定的逻辑名称。
     * @return the implementation instance, or null if no matching name is found.
     *         实现实例，如果没有找到匹配的名称则返回 null。
     */
    fun <T : Any> loadByName(serviceClass: Class<T>, name: String): T? {
        ensureInitialized()
        return registry.getService(serviceClass, name)
    }

    /**
     * Check whether any implementation is registered for [serviceClass].
     * 检查 [serviceClass] 是否注册了任何实现。
     *
     * @param serviceClass the service interface [Class]. 服务接口的 [Class]。
     * @return true if at least one implementation is registered. 如果至少注册了一个实现则返回 true。
     */
    fun <T : Any> isRegistered(serviceClass: Class<T>): Boolean {
        ensureInitialized()
        return registry.hasService(serviceClass)
    }

    /**
     * Get the underlying [ServiceRegistry] for advanced use cases.
     * 获取底层的 [ServiceRegistry] 用于高级用例。
     *
     * The registry is initialized before being returned.
     * 注册表在返回之前会被初始化。
     */
    fun getRegistry(): ServiceRegistry {
        ensureInitialized()
        return registry
    }

    /**
     * Reset the SPI framework to its uninitialized state.
     * 将 SPI 框架重置为未初始化状态。
     *
     * This clears all registrations and resets the initialization flag.
     * Primarily useful for testing.
     * 清除所有注册并重置初始化标志。主要用于测试。
     */
    fun reset() {
        synchronized(initLock) {
            registry.clear()
            initialized = false
        }
    }

    /**
     * Dump a human-readable snapshot of all registered services for debugging.
     * Useful for troubleshooting "why isn't my service being discovered?" issues.
     * 输出所有已注册服务的人类可读快照，用于调试。
     * 适用于排查"为什么我的服务没有被发现？"这类问题。
     *
     * Usage / 用法:
     * ```kotlin
     * SpiLoader.initialize()
     * println(SpiLoader.dump())
     * ```
     *
     * @see ServiceRegistry.dump
     */
    fun dump(): String {
        ensureInitialized()
        return registry.dump()
    }

    /**
     * Load the highest-priority implementation of [T].
     * Kotlin reified convenience method — no Class<T> parameter needed.
     * 加载 [T] 的最高优先级实现。Kotlin reified 便捷方法，无需传递 Class<T> 参数。
     */
    inline fun <reified T : Any> load(): T = load(T::class.java)

    /**
     * Load all implementations of [T], ordered by priority descending.
     * 加载 [T] 的所有实现，按优先级降序排列。
     */
    inline fun <reified T : Any> loadAll(): List<T> = loadAll(T::class.java)

    /**
     * Load a specific named implementation of [T].
     * 加载 [T] 的指定名称实现。
     */
    inline fun <reified T : Any> loadByName(name: String): T? = loadByName(T::class.java, name)

    /**
     * Check whether any implementation is registered for [T].
     * 检查 [T] 是否注册了任何实现。
     */
    inline fun <reified T : Any> isRegistered(): Boolean = isRegistered(T::class.java)
}
