package com.spi.sample

import android.os.Bundle
import android.util.Log
import android.widget.Button
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.spi.framework.core.SpiLoader
import com.spi.framework.core.ServiceNotFoundException
import com.spi.sample.api.GreetingService

/**
 * Demonstrates the SPI Framework's three loading methods:
 * 演示 SPI 框架的三种加载方法：
 *
 * 1. [SpiLoader.load] — highest-priority implementation / 最高优先级实现
 * 2. [SpiLoader.loadAll] — all implementations, priority-sorted / 所有实现，按优先级排序
 * 3. [SpiLoader.loadByName] — a specific named implementation / 指定名称的实现
 *
 * **Decoupling note / 解耦说明**: MainActivity only depends on **sample-api** (the interface module).
 * It NEVER imports or references implementation classes (e.g., EnglishGreeting, SpanishGreeting).
 * Implementations are discovered through [SpiLoader] at runtime via the SPI mechanism.
 * This demonstrates true module decoupling: the business app knows only the API, never the impl.
 * MainActivity 仅依赖 **sample-api**（接口模块）。
 * 它从不导入或引用实现类（如 EnglishGreeting, SpanishGreeting）。
 * 实现通过 [SpiLoader] 在运行时通过 SPI 机制发现。
 * 这展示了真正的模块解耦：业务应用只知道 API，从不知道实现。
 */
class MainActivity : AppCompatActivity(R.layout.activity_main) {

    private lateinit var tvLoadResult: TextView
    private lateinit var tvLoadAllResult: TextView
    private lateinit var tvLoadByNameResult: TextView
    private lateinit var tvError: TextView
    private lateinit var btnRefresh: Button

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        tvLoadResult = findViewById(R.id.tv_load_result)
        tvLoadAllResult = findViewById(R.id.tv_load_all_result)
        tvLoadByNameResult = findViewById(R.id.tv_load_by_name_result)
        tvError = findViewById(R.id.tv_error)
        btnRefresh = findViewById(R.id.btn_refresh)

        btnRefresh.setOnClickListener { runDemo() }

        runDemo()
    }

    private fun runDemo() {
        // Clear previous results and errors / 清除之前的结果和错误
        tvLoadResult.text = ""
        tvLoadAllResult.text = ""
        tvLoadByNameResult.text = ""
        tvError.text = ""
        tvError.visibility = TextView.GONE

        try {
            // Step 1: Initialize the SPI registry.
            // This uses ServiceLoader to discover ServiceIndexProvider
            // implementations generated by the KSP processor.
            // 步骤 1: 初始化 SPI 注册表。
            // 这使用 ServiceLoader 来发现由 KSP 处理器生成的 ServiceIndexProvider 实现。
            SpiLoader.initialize()

            // Debug: dump the registry to logcat for troubleshooting
            // 调试：将注册表快照输出到 logcat 以便排查问题
            Log.d("SPI", SpiLoader.dump())

            // Step 2: Demonstrate SpiLoader.load() — returns the highest-priority
            // implementation (priority = 10 => EnglishGreeting).
            // 步骤 2: 演示 SpiLoader.load() — 返回最高优先级实现（priority = 10 => EnglishGreeting）。
            val best: GreetingService = SpiLoader.load(GreetingService::class.java)
            tvLoadResult.text = getString(
                R.string.format_load,
                best.greet()
            )

            // Step 3: Demonstrate SpiLoader.loadAll() — returns all implementations
            // sorted by priority descending.
            // 步骤 3: 演示 SpiLoader.loadAll() — 返回所有实现，按优先级降序排序。
            val all: List<GreetingService> = SpiLoader.loadAll(GreetingService::class.java)
            tvLoadAllResult.text = all.joinToString("\n") { service ->
                "  - ${service.greet()}"
            }

            // Step 4: Demonstrate SpiLoader.loadByName() — returns a specific
            // named implementation.
            // 步骤 4: 演示 SpiLoader.loadByName() — 返回指定名称的实现。
            val spanish: GreetingService? = SpiLoader.loadByName(
                GreetingService::class.java,
                "spanish"
            )
            if (spanish != null) {
                tvLoadByNameResult.text = getString(
                    R.string.format_load_by_name,
                    "spanish",
                    spanish.greet()
                )
            } else {
                tvLoadByNameResult.text = getString(R.string.format_not_found, "spanish")
            }

            // Also demonstrate loading by a non-existent name.
            // 同时演示按不存在的名称加载。
            val unknown: GreetingService? = SpiLoader.loadByName(
                GreetingService::class.java,
                "french"
            )
            tvLoadResult.append("\n(" + getString(R.string.format_not_found, "french") + ")")

        } catch (e: ServiceNotFoundException) {
            tvError.text = getString(R.string.format_error, e.message ?: e.toString())
            tvError.visibility = TextView.VISIBLE
        } catch (e: Exception) {
            tvError.text = getString(R.string.format_error, e.message ?: e.toString())
            tvError.visibility = TextView.VISIBLE
        }
    }
}
